//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod zosta³ wygenerowany przez narzêdzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mog¹ spowodowaæ nieprawid³owe zachowanie i zostan¹ utracone, jeœli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt3_Janusz70130.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagaj¹ca zdefiniowania typu do wyszukiwania zlokalizowanych ci¹gów itd.
    /// </summary>
    // Ta klasa zosta³a automatycznie wygenerowana za pomoc¹ klasy StronglyTypedResourceBuilder
    // przez narzêdzie, takie jak ResGen lub Visual Studio.
    // Aby dodaæ lub usun¹æ sk³adow¹, edytuj plik ResX, a nastêpnie ponownie uruchom narzêdzie ResGen
    // z opcj¹ /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wyst¹pienie ResourceManager u¿ywane przez tê klasê.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Projekt3_Janusz70130.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przes³ania w³aœciwoœæ CurrentUICulture bie¿¹cego w¹tku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomoc¹ tej klasy zasobów wymagaj¹cej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
    }
}
