//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod zosta³ wygenerowany przez narzêdzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mog¹ spowodowaæ nieprawid³owe zachowanie i zostan¹ utracone, jeœli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt3_Janusz70130.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
